name: Build CI

on:
  push:
    branches: 
      - master

  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ExecShell
      run : |
          apt-get install mkisofs
          chmod +x mkvhdboot.sh
          ./mkvhdboot.sh
          ls
        
    - uses: actions/upload-artifact@v4
      with: 
        path: "ventoy_vhdboot.img"
